### ISSUE TITLE
CREST fmriprep: FAST subs

### ISSUE THREAD

**Issue by ariveradompenciel** [HBClab/SoftwareIssues#14]
### Script/Job File

```
#!/bin/bash

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M adriana-rivera-dompenciel@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/CREST/code/fmriprep/out/
#$ -e /Shared/vosslabhpc/Projects/CREST/code/fmriprep/err/
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg \
/mnt/Projects/CREST/ /mnt/Projects/CREST/derivatives \
participant --participant_label FAST913 \
-w /nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep \
--write-graph --mem_mb 35000 --omp-nthreads 10 --nthreads 16 --use-aroma \
--output-space template \
--template MNI152NLin2009cAsym \
--fs-license-file /mnt/UniversalSoftware/freesurfer_license.txt
```

### Email Message

```
Job 981403 (sub-FAST913.job) Complete
User             = sodoma
Queue            = UI@argon-itf-cf45-29.hpc
Host             = argon-itf-cf45-29.hpc
Start Time       = 05/20/2020 09:49:42
End Time         = 05/20/2020 09:49:50
User Time        = 00:00:01
System Time      = 00:00:01
Wallclock Time   = 00:00:08
CPU              = 00:00:05
Max vmem         = 273.312M
Exit Status      = 1
```

### Output File

NO OUTPUT!

### Error (stderr file)

```
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 464, in build_workflow
    os.makedirs(work_dir, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/nfsscratch/Users/ariveradompenciel/work'
```

**Comment by jdkent** [comment]
I would examine the output of this command:
```
singularity exec -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg touch /nfsscratch/Users/ariveradompenciel/work/this.txt
```
and this command
```
singularity exec -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg mkdir /nfsscratch/Users/ariveradompenciel/testDirectory
```
(remove the directory and file after you make them if the commands are successful)

then run the same commands without using singularity to see if the error remains:
`mkdir /nfsscratch/Users/ariveradompenciel/testDirectory`
`touch /nfsscratch/Users/ariveradompenciel/work/this.txt`

Then we can tell how reproducible the error is, and under what contexts the error occurs.

**Comment by ariveradompenciel** [comment]
commands with and without singularity worked completely fine, did not run into any issues!

**Comment by ariveradompenciel** [comment]
ran commands with and without singularity with no errors! just to be sure, am I supposed to re-run at least one FAST sub now to see if I still get error?

**Comment by jdkent** [comment]
If all those had no errors, then I would try re-running this participant again, perhaps there was just weird error where multiple computers were writing to the same place at the same time, or some type of asynchrony between file writing/reading, but I don't know since the error does not appear to be reproducible.

**Comment by jdkent** [comment]
Here was the reason for the error.

The user running the job (`sodoma`), does not have access to the directory `/nfsscratch/Users/ariveradompenciel` (as expected), but `sodoma` should have access to the directory `/nfsscratch/Users/sodoma`, so that's where the working directory should be.

**Comment by ariveradompenciel** [comment]
After clarifying that another user (sodoma) ran this code for me to help divide up the large list of FAST subs, I would like to show the code I sent him to run:

### Create .job files for subs:
```
for sub in $(cat /Shared/vosslabhpc/Projects/CREST/derivatives/sublists/sublist_fast1.txt); do
    echo ${sub}
    subname=$(basename ${sub} | sed "s/sub-//");
    echo $subname
    sed -e 's|SUBJECT|'"${subname}"'|g' -e 's|mwvoss|ariveradompenciel|g' -e 's|michelle-voss@uiowa.edu|adriana-rivera-dompenciel@uiowa.edu|g' TEMPLATE_fmriprep.job > ${PWD}/sub-${subname}.job
done
```

### Submit as job in argon:
```
for job in $(cat /Shared/vosslabhpc/Projects/CREST/derivatives/sublists/argon_sublist_fast1.txt); do 
    echo ${job}
    qsub ${job}
done
```

Regarding the first code to create the .job files, I wonder if this specific bit here: ```sed -e 's|mwvoss|ariveradompenciel|g'``` is the culprit.

**Comment by jdkent** [comment]
yep, you're right, I would say replacing `sed -e 's|mwvoss|ariveradompenciel|g'` with `sed -e 's|mwvoss|sodoma|g'` would fix it.
