### ISSUE TITLE
CREST fmriprep: FAST906

### ISSUE THREAD

**Issue by ariveradompenciel** [HBClab/SoftwareIssues#15]
This sub was a test run by user sodoma who is helping user ariveradompenciel in pre-processing the large FAST sublist.

### Script/Job File

```
#!/bin/bash

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M adriana-rivera-dompenciel@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/CREST/code/fmriprep/out/
#$ -e /Shared/vosslabhpc/Projects/CREST/code/fmriprep/err/
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg \
/mnt/Projects/CREST/ /mnt/Projects/CREST/derivatives \
participant --participant_label FAST906 \
-w /nfsscratch/Users/sodoma/work/CRESTfmriprep \
--write-graph --mem_mb 35000 --omp-nthreads 10 --nthreads 16 --use-aroma \
--output-space template \
--template MNI152NLin2009cAsym \
--fs-license-file /mnt/UniversalSoftware/freesurfer_license.txt
```

### Email Message

```
Job 1022341 (sub-FAST906.job) Complete
User             = sodoma
Queue            = UI@argon-lc-g11-19.hpc
Host             = argon-lc-g11-19.hpc
Start Time       = 05/21/2020 12:52:57
End Time         = 05/21/2020 12:53:20
User Time        = 00:00:02
System Time      = 00:00:02
Wallclock Time   = 00:00:23
CPU              = 00:00:10
Max vmem         = 311.656M
Exit Status      = 1
```

### Output File

```
200521-12:53:09,957 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.1:
      * BIDS dataset path: /mnt/Projects/CREST.
      * Participant list: ['FAST906'].
      * Run identifier: 20200521-125309_07f9b137-54d5-4796-980c-8caf819186da.
    
200521-12:53:09,958 nipype.workflow WARNING:
	 Option --debug is deprecated and has no effect
200521-12:53:20,282 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/mnt/Projects/CREST/sub-FAST906/func/sub-FAST906_task-rest_bold.nii.gz" (0.03 GB / 180 TRs). Memory resampled/largemem=0.10/0.15 GB.
200521-12:53:20,311 nipype.workflow IMPORTANT:
	 No single-band-reference found for sub-FAST906_task-rest_bold.nii.gz
```

### Error (stderr file)

```
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 553, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 211, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 496, in init_single_subject_wf
    num_bold=len(subject_data['bold']))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/bold/base.py", line 365, in init_func_preproc_wf
    pe_direction=metadata.get("PhaseEncodingDirection")),
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 728, in __init__
    from_file=from_file, resource_monitor=resource_monitor, **inputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 179, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/specs.py", line 66, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'pe_direction' trait of a FunctionalSummaryInputSpec instance must be None or 'i' or 'i-' or 'j' or 'j-', but a value of 'y-' <class 'str'> was specified.
```

**Comment by jdkent** [comment]
in most cases, `y-` _should_ translate to `j-`, but it never hurts to [re-read this helpful page on the matter](https://nipy.org/nibabel/coordinate_systems.html), so the solution will be changing the participant `json` files for all the functional images that have `y-` changed to `j-`.

You can also read [this section of the bids-specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#in-plane-spatial-encoding) to know what value(s) are expected for `PhaseEncodingDirection` in the participant functional json files.
