### ISSUE TITLE
CREST fmriprep: no BOLD images found (FAST)

### ISSUE THREAD

**Issue by ariveradompenciel** [HBClab/SoftwareIssues#18]
### Script/Job File

```
#!/bin/bash

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M adriana-rivera-dompenciel@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/CREST/code/fmriprep/out/
#$ -e /Shared/vosslabhpc/Projects/CREST/code/fmriprep/err/
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg \
/mnt/Projects/CREST/ /mnt/Projects/CREST/derivatives \
participant --participant_label FAST1053 \
-w /nfsscratch/Users/sodoma/work/CRESTfmriprep \
--write-graph --mem_mb 35000 --omp-nthreads 10 --nthreads 16 --use-aroma \
--output-space template \
--template MNI152NLin2009cAsym \
--fs-license-file /mnt/UniversalSoftware/freesurfer_license.txt
```

### Email Message

```
Job 1320779 (sub-FAST1053.job) Complete
User             = sodoma
Queue            = UI@argon-itf-cf45-34.hpc
Host             = argon-itf-cf45-34.hpc
Start Time       = 06/03/2020 03:08:03
End Time         = 06/03/2020 03:08:20
User Time        = 00:00:01
System Time      = 00:00:01
Wallclock Time   = 00:00:17
CPU              = 00:00:07
Max vmem         = 309.777M
Exit Status      = 1
```

### Output File

```
200603-03:08:14,752 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.1:
      * BIDS dataset path: /mnt/Projects/CREST.
      * Participant list: ['FAST1053'].
      * Run identifier: 20200603-030814_a2db3e2d-9f2a-4ae0-ad40-34239bcb71ca.
    
200603-03:08:14,752 nipype.workflow WARNING:
	 Option --debug is deprecated and has no effect
```

### Error (stderr file)

```
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 553, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 211, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 379, in init_single_subject_wf
    subject_id, task_id if task_id else '<all>'))
Exception: No BOLD images found for participant FAST1053 and task <all>. All workflows require BOLD images.
```

**Comment by jdkent** [comment]
When I looked in this directory:
`<vosslabhpc_mount>/Projects/CREST/sub-FAST1040/func/`

All I saw was the `json` file, but no `nifti` file:
```
$ ls
> sub-FAST1040_task-rest_bold.json
```

So the nifti files must have not been copied over properly (or don't exist??). fmriprep by default does not run without a bold nifti and json file existing in the necessary directory.
