### ISSUE TITLE
BETTER fmriprep: permission error

### ISSUE THREAD

**Issue by jdkent** [HBClab/SoftwareIssues#4]
### Script/Job File

copy/paste the script below between [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)

```
#!/bin/bash

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M james-kent@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/fmriprep/out/
#$ -e /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/fmriprep/err/
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg \
/mnt/Projects/BETTER/3-Experiment/2-data/bids/ /mnt/Projects/BETTER/3-Experiment/2-data/bids/derivatives \
participant --participant_label GE120075 \
-w /nfsscratch/Users/jdkent/work/BETTERfmriprep \
--write-graph --mem_mb 35000 --omp-nthreads 10 --nthreads 16 --use-aroma \
--output-space template \
--template MNI152NLin2009cAsym \
--fs-license-file /mnt/UniversalSoftware/freesurfer_license.txt
```

### Email Message

copy/paste the email error message you received between [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)
```
Job 4496733 (sub-GE120075.job) Complete
 User             = jdkent
 Queue            = UI@argon-itf-cf45-26.hpc
 Host             = argon-itf-cf45-26.hpc
 Start Time       = 03/01/2020 00:55:19
 End Time         = 03/01/2020 12:08:58
 User Time        = 01:10:00
 System Time      = 00:00:55
 Wallclock Time   = 11:13:39
 CPU              = 39:57:34
 Max vmem         = 21.703G
 Exit Status      = 1
```

### Output File

If you specified `#$ -o /Shared/vosslabhpc/projects/some/project/directory/` in your job file,
find the corresponding output file and paste it here [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks).
(if you know where the relevant error occurred you can just paste that section instead of the entire file)
```
200301-12:08:37,766 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_GE120075_wf.func_preproc_ses_post_task_taskswitch_wf.ica_aroma_wf.add_nonsteady".
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```
### Error (stderr file)

If you specified `#$ -e /Shared/vosslabhpc/projects/some/project/directory/` in your job file,
find the corresponding output file and paste it here [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks).

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 351, in main
    write_derivative_description(bids_dir, str(Path(output_dir) / 'fmriprep'))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 243, in write_derivative_description
    with open(os.path.join(deriv_dir, 'dataset_description.json'), 'w') as fobj:
PermissionError: [Errno 13] Permission denied: '/mnt/Projects/BETTER/3-Experiment/2-data/bids/derivatives/fmriprep/dataset_description.json'
```

**Comment by jdkent** [comment]
This appears strange, so first I am re-running without change to see if the same error happens again.
EDIT: this should be because the dataset_description file was under git annex and locked, running `git annex uninit` should fix the problem, will close if that turns out to be true.

**Comment by jdkent** [comment]
in addition to running `git annex uninit dataset_description.json` I needed to run `chmod ug+wrx description.json`, to give myself and other group members access to the file.
