### ISSUE TITLE
BETTER fmriprep: incomplete file

### ISSUE THREAD

**Issue by jdkent** [HBClab/SoftwareIssues#6]
### Script/Job File

copy/paste the script below between [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)
```
#!/bin/bash

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M james-kent@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/fmriprep/out/
#$ -e /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/fmriprep/err/
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg \
/mnt/Projects/BETTER/3-Experiment/2-data/bids/ /mnt/Projects/BETTER/3-Experiment/2-data/bids/derivatives \
participant --participant_label GE120058 \
-w /nfsscratch/Users/jdkent/work/BETTERfmriprep \
--write-graph --mem_mb 35000 --omp-nthreads 10 --nthreads 16 --use-aroma \
--output-space template \
--template MNI152NLin2009cAsym \
--fs-license-file /mnt/UniversalSoftware/freesurfer_license.txt
```
### Email Message

copy/paste the email error message you received between [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)
```
Job 5892290 (sub-GE120058.job) Complete
 User             = jdkent
 Queue            = UI@argon-itf-cf52-33.hpc
 Host             = argon-itf-cf52-33.hpc
 Start Time       = 03/19/2020 21:38:49
 End Time         = 03/19/2020 21:39:22
 User Time        = 00:00:01
 System Time      = 00:00:01
 Wallclock Time   = 00:00:33
 CPU              = 00:00:16
 Max vmem         = 332.156M
 Exit Status      = 1
```

### Output File

If you specified `#$ -o /Shared/vosslabhpc/projects/some/project/directory/` in your job file,
find the corresponding output file and paste it here [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks).
(if you know where the relevant error occurred you can just paste that section instead of the entire file)
```
200319-21:39:03,335 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.1:
      * BIDS dataset path: /mnt/Projects/BETTER/3-Experiment/2-data/bids.
      * Participant list: ['GE120058'].
      * Run identifier: 20200319-213903_bac4de99-8dae-44c6-bbd0-8b56782662bf.
    
200319-21:39:03,335 nipype.workflow WARNING:
	 Option --debug is deprecated and has no effect
200319-21:39:13,687 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/mnt/Projects/BETTER/3-Experiment/2-data/bids/sub-GE120058/ses-post/func/sub-GE120058_ses-post_task-rest_run-1_bold.nii.gz" (0.03 GB / 240 TRs). Memory resampled/largemem=0.12/0.19 GB.
200319-21:39:13,714 nipype.workflow IMPORTANT:
	 No single-band-reference found for sub-GE120058_ses-post_task-rest_run-1_bold.nii.gz
200319-21:39:15,496 nipype.workflow IMPORTANT:
	 Slice-timing correction will be included.
200319-21:39:15,519 nipype.workflow WARNING:
	 SDC: no fieldmaps found or they were ignored (/mnt/Projects/BETTER/3-Experiment/2-data/bids/sub-GE120058/ses-post/func/sub-GE120058_ses-post_task-rest_run-1_bold.nii.gz).
200319-21:39:18,637 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/mnt/Projects/BETTER/3-Experiment/2-data/bids/sub-GE120058/ses-post/func/sub-GE120058_ses-post_task-rest_run-2_bold.nii.gz" (0.03 GB / 8485 TRs). Memory resampled/largemem=0.11/2.49 GB.
200319-21:39:18,665 nipype.workflow IMPORTANT:
	 No single-band-reference found for sub-GE120058_ses-post_task-rest_run-2_bold.nii.gz
200319-21:39:19,92 nipype.workflow WARNING:
	 SDC: no fieldmaps found or they were ignored (/mnt/Projects/BETTER/3-Experiment/2-data/bids/sub-GE120058/ses-post/func/sub-GE120058_ses-post_task-rest_run-2_bold.nii.gz).
200319-21:39:22,217 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/mnt/Projects/BETTER/3-Experiment/2-data/bids/sub-GE120058/ses-post/func/sub-GE120058_ses-post_task-taskswitch_bold.nii.gz" (0.00 GB / 471 TRs). Memory resampled/largemem=0.00/0.00 GB.
200319-21:39:22,243 nipype.workflow IMPORTANT:
	 No single-band-reference found for sub-GE120058_ses-post_task-taskswitch_bold.nii.gz
```

### Error (stderr file)

If you specified `#$ -e /Shared/vosslabhpc/projects/some/project/directory/` in your job file,
find the corresponding output file and paste it here [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks).
```
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 553, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 211, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 496, in init_single_subject_wf
    num_bold=len(subject_data['bold']))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/bold/base.py", line 302, in init_func_preproc_wf
    (_get_series_len(ref_file) > 4 or "TooShort"))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/bold/base.py", line 980, in _get_series_len
    skip_vols = _get_vols_to_discard(img)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/registration.py", line 421, in _get_vols_to_discard
    data_slice = img.dataobj[:, :, :, :50]
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 367, in __getitem__
    lock=self._lock)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/fileslice.py", line 791, in fileslice
    arr_data = read_segments(fileobj, segments, n_bytes, lock)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/fileslice.py", line 682, in read_segments
    raise ValueError("Whoops, not enough data in file")
ValueError: Whoops, not enough data in file
```

**Comment by jdkent** [comment]
relevant error message `ValueError: Whoops, not enough data in file`, this means one the files in the bids dataset is corrupt and needs to be recopied.
