### ISSUE TITLE
BETTER mriqc: corrupt file

### ISSUE THREAD

**Issue by jdkent** [HBClab/SoftwareIssues#7]
### Script/Job File

copy/paste the script below between [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)
```
#!/bin/sh

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M james-kent@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/mriqc/out
#$ -e /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/mriqc/err
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/poldracklab_mriqc_0.10.4-2018-03-23-26b58c18952f.img \
/mnt/Projects/BETTER/3-Experiment/2-data/bids/ /mnt/Projects/BETTER/3-Experiment/2-data/bids/derivatives/mriqc \
participant --participant_label GE120075 --session-id pre \
-w /nfsscratch/Users/jdkent/work/BETTERmriqc \
--n_procs 10 --mem_gb 35 --write-graph \
--fd_thres 0.5 --start-idx 4
```
### Email Message

copy/paste the email error message you received between [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)
```
Job 7329304 (sub-GE120075_ses-pre.job) Complete
 User             = jdkent
 Queue            = UI@argon-itf-cf50-33.hpc
 Host             = argon-itf-cf50-33.hpc
 Start Time       = 10/31/2019 09:31:18
 End Time         = 10/31/2019 10:28:12
 User Time        = 01:08:10
 System Time      = 00:02:08
 Wallclock Time   = 00:56:54
 CPU              = 01:10:19
 Max vmem         = 6.556G
 Exit Status      = 1
```

### Output File

If you specified `#$ -o /Shared/vosslabhpc/projects/some/project/directory/` in your job file,
find the corresponding output file and paste it here [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks).
(if you know where the relevant error occurred you can just paste that section instead of the entire file)
```
2019-10-31 10:09:37,744 mriqc.cli:WARNING No T2w scans were found in /mnt/Projects/BETTER/3-Experiment/2-data/bids
2019-10-31 10:09:37,745 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.
2019-10-31 10:09:38,993 workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.non_steady_state_detector" (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-taskswitch_bold.nii.gz/non_steady_state_detector)
2019-10-31 10:09:40,856 workflow:ERROR Node non_steady_state_detector.a2 failed to run on host argon-itf-cf50-33.hpc.
2019-10-31 10:09:40,857 workflow:ERROR Saving crash info to /mnt/Projects/BETTER/3-Experiment/2-data/bids/derivatives/mriqc/logs/crash-20191031-100940-jdkent-non_steady_state_detector.a2-21aae026-7f05-4dab-860a-571f6ad4e8b1.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 836, in _run_interface
    global_signal = in_nii.get_data()[:, :, :, :50].mean(axis=0).mean(
IndexError: too many indices for array

2019-10-31 10:14:25,117 niworkflows:INFO Estimating initial transform using AffineInitializer
2019-10-31 10:14:26,302 niworkflows:INFO Estimating initial transform using AffineInitializer
2019-10-31 10:15:53,187 niworkflows:INFO Terminal outputs of initialization saved (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPI2MNI/stderr.nipype-init).
2019-10-31 10:15:53,189 niworkflows:INFO Loading settings from file /usr/local/miniconda/lib/python3.6/site-packages/niworkflows/data/epi-mni_registration_precise_000.json.
2019-10-31 10:15:53,193 niworkflows:INFO Retry #1, commandline: 
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 0 --initial-moving-transform [ /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPI2MNI/transform.mat, 0 ] --initialize-transforms-per-stage 0 --interpolation LanczosWindowedSinc --output [ epi_to_mni, epi_to_mni_Warped.nii.gz ] --transform Rigid[ 0.05 ] --metric Mattes[ /usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPIApplyMask/sub-GE120075_ses-pre_task-rest_run-2_bold_valid_calc_volreg_tstat_corrected_masked.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 10000x1000x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x1.0vox --shrink-factors 4x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Affine[ 0.08 ] --metric Mattes[ /usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPIApplyMask/sub-GE120075_ses-pre_task-rest_run-2_bold_valid_calc_volreg_tstat_corrected_masked.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 500x250x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x1.0vox --shrink-factors 8x4x2 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform SyN[ 0.1, 3.0, 0.0 ] --metric CC[ /usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPIApplyMask/sub-GE120075_ses-pre_task-rest_run-2_bold_valid_calc_volreg_tstat_corrected_masked.nii.gz, 1, 4, None, 1 ] --convergence [ 100x30x20, 1e-06, 10 ] --smoothing-sigmas 3.0x2.0x1.0vox --shrink-factors 8x4x2 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.005, 0.995 ]  --write-composite-transform 1
2019-10-31 10:15:57,254 niworkflows:INFO Loading settings from file /usr/local/miniconda/lib/python3.6/site-packages/niworkflows/data/epi-mni_registration_precise_000.json.
2019-10-31 10:15:57,261 niworkflows:INFO Retry #1, commandline: 
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 0 --initial-moving-transform [ /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-1_bold.nii.gz/EPI2MNI/transform.mat, 0 ] --initialize-transforms-per-stage 0 --interpolation LanczosWindowedSinc --output [ epi_to_mni, epi_to_mni_Warped.nii.gz ] --transform Rigid[ 0.05 ] --metric Mattes[ /usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-1_bold.nii.gz/EPIApplyMask/sub-GE120075_ses-pre_task-rest_run-1_bold_valid_calc_volreg_tstat_corrected_masked.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 10000x1000x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x1.0vox --shrink-factors 4x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Affine[ 0.08 ] --metric Mattes[ /usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-1_bold.nii.gz/EPIApplyMask/sub-GE120075_ses-pre_task-rest_run-1_bold_valid_calc_volreg_tstat_corrected_masked.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 500x250x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x1.0vox --shrink-factors 8x4x2 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform SyN[ 0.1, 3.0, 0.0 ] --metric CC[ /usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-1_bold.nii.gz/EPIApplyMask/sub-GE120075_ses-pre_task-rest_run-1_bold_valid_calc_volreg_tstat_corrected_masked.nii.gz, 1, 4, None, 1 ] --convergence [ 100x30x20, 1e-06, 10 ] --smoothing-sigmas 3.0x2.0x1.0vox --shrink-factors 8x4x2 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.005, 0.995 ]  --write-composite-transform 1
2019-10-31 10:16:37,557 interface:WARNING QC metrics failed to upload. Status 1: QC metrics failed to upload due to connection error shown below:
HTTPSConnectionPool(host='mriqc.nimh.nih.gov', port=443): Max retries exceeded with url: /api/v1/bold (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b6eee43b5f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
2019-10-31 10:16:51,766 interface:WARNING QC metrics failed to upload. Status 1: QC metrics failed to upload due to connection error shown below:
HTTPSConnectionPool(host='mriqc.nimh.nih.gov', port=443): Max retries exceeded with url: /api/v1/bold (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b6eefd88cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
2019-10-31 10:16:57,447 niworkflows:INFO Estimating initial transform using AffineInitializer
2019-10-31 10:19:06,479 niworkflows:INFO Successful spatial normalization (retry #1).
2019-10-31 10:19:06,481 niworkflows:INFO Report - setting fixed (/usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz) and moving (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPI2MNI/epi_to_mni_Warped.nii.gz) images
2019-10-31 10:19:06,482 niworkflows:INFO Generating visual report
2019-10-31 10:19:12,056 niworkflows:INFO Successful spatial normalization (retry #1).
2019-10-31 10:19:12,059 niworkflows:INFO Report - setting fixed (/usr/local/miniconda/lib/python3.6/site-packages/mriqc/data/mni/2mm_T2_brain.nii.gz) and moving (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-1_bold.nii.gz/EPI2MNI/epi_to_mni_Warped.nii.gz) images
2019-10-31 10:19:12,059 niworkflows:INFO Generating visual report
2019-10-31 10:19:29,665 niworkflows:INFO Successfully created report (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-2_bold.nii.gz/EPI2MNI/report.svg)
2019-10-31 10:19:33,947 niworkflows:INFO Successfully created report (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..func..sub-GE120075_ses-pre_task-rest_run-1_bold.nii.gz/EPI2MNI/report.svg)
2019-10-31 10:19:43,393 mriqc.report:WARNING Building bold report: no exclude index was found
2019-10-31 10:19:55,807 niworkflows:INFO Loading settings from file /usr/local/miniconda/lib/python3.6/site-packages/niworkflows/data/t1-mni_registration_fast_000.json.
2019-10-31 10:19:55,813 niworkflows:INFO Retry #1, commandline: 
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 0 --initial-moving-transform [ /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/transform.mat, 0 ] --initialize-transforms-per-stage 0 --interpolation LanczosWindowedSinc --output [ ants_t1_to_mni, ants_t1_to_mni_Warped.nii.gz ] --transform Rigid[ 0.01 ] --metric Mattes[ /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/fixed_masked.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/moving_masked.nii.gz, 1, 32, Random, 0.15 ] --convergence [ 1000, 1e-06, 20 ] --smoothing-sigmas 4.0vox --shrink-factors 4 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Affine[ 0.08 ] --metric Mattes[ /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/fixed_masked.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/moving_masked.nii.gz, 1, 32, Regular, 0.15 ] --convergence [ 500x250x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x0.0vox --shrink-factors 4x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform SyN[ 0.1, 3.0, 0.0 ] --metric Mattes[ /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/fixed_masked.nii.gz, /nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/moving_masked.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 50x20, 1e-06, 10 ] --smoothing-sigmas 1.0x0.0vox --shrink-factors 2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.0, 1.0 ]  --write-composite-transform 1
2019-10-31 10:19:56,423 mriqc.report:WARNING Building bold report: no exclude index was found
2019-10-31 10:23:52,776 niworkflows:INFO Successful spatial normalization (retry #1).
2019-10-31 10:23:59,944 niworkflows:INFO Report - setting fixed (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/fixed_masked.nii.gz) and moving (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/ants_t1_to_mni_Warped.nii.gz) images
2019-10-31 10:23:59,945 niworkflows:INFO Generating visual report
2019-10-31 10:24:23,750 niworkflows:INFO Successfully created report (/nfsscratch/Users/jdkent/work/BETTERmriqc/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..mnt..Projects..BETTER..3-Experiment..2-data..bids..sub-GE120075..ses-pre..anat..sub-GE120075_ses-pre_T1w.nii.gz/SpatialNormalization/report.svg)
2019-10-31 10:28:08,885 interface:WARNING QC metrics failed to upload. Status 1: QC metrics failed to upload due to connection error shown below:
HTTPSConnectionPool(host='mriqc.nimh.nih.gov', port=443): Max retries exceeded with url: /api/v1/T1w (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b6d7e75a5f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
2019-10-31 10:28:12,110 workflow:ERROR could not run node: workflow_enumerator.funcMRIQC.non_steady_state_detector.a2
```

### Error (stderr file)

If you specified `#$ -e /Shared/vosslabhpc/projects/some/project/directory/` in your job file,
find the corresponding output file and paste it here [triple backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks).
```
/usr/local/miniconda/lib/python3.6/site-packages/grabbit/core.py:410: UserWarning: No valid root directory found for domain 'derivatives'. Falling back on the Layout's root directory. If this isn't the intended behavior, make sure the config file for this domain includes a 'root' key.
  "'root' key." % config['name'])
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.10.4', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 316, in main
    workflow.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 602, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 198, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/tools.py", line 78, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

**Comment by jdkent** [comment]
The file was corrupt and needed to be redownloaded/recopied.
